### PR TITLE
fix: allow posting on pull-requests

### LINKED ISSUE #63: Add posting to pull-request review comment capability
The SDK should be able to post to pull-request threads. The API is a bit different for these as it should directly use `pull` from the REST API.

What happens right now:
- if "pull_request" is present in the payload, try to post to the pull-request itself
- if we wanted to post to the thread, we would need to use `octokit.rest.pulls.createReplyForReviewComment` or `createReviewComment`
- same thing goes for updating the comment that needs a different API
- maybe we could consider having an extra argument in the options to specify a pull-request comment ID

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #63
QA: https://github.com/Meniole/plugin-template/pull/3

### CODE REVIEW

File: src/comment.ts [hunk 1]
```diff
@@ -17,117 +18,192 @@ export interface CommentOptions {
...
-    instigatorName = context.payload.installation?.account?.name;
-  } else {
-    instigatorName = context.payload.sender?.login || HEADER_NAME;
+  const metadata = message.metadata
+    ? {
+        message: message.metadata.message,
+        stack: message.metadata.stack || message.metadata.error?.stack,
+        caller: message.metadata.caller || message.metadata.error?.stack?.split("\n")[2]?.match(/at (\S+)/)?.[1],
+      }
+    : { ...message };
```
Comment (whilefoo) [inline src/comment.ts:138]: If I use `logger.ok("something", { first: 1, second: 2 })`, the metadata I provided won't be in the comment metadata. Was this intended from the beginning?

File: src/comment.ts [hunk 2]
```diff
@@ -5,6 +5,7 @@ import { PluginRuntimeInfo } from "./helpers/runtime-info";
 import { sanitizeMetadata } from "./util";
 
 const HEADER_NAME = "UbiquityOS";
+const lastCommentId = { reviewCommentId: null as number | null, issueCommentId: null as number | null };
```
Comment (whilefoo) [inline src/comment.ts:8]: I'm concerned that this can lead to some bugs. If I understand correctly Cloudflare workers sometimes run multiple requests in the same instance of the worker , so if two requests were posting comments it would cause some of them to get comment id from another request.

**Review by whilefoo — COMMENTED** [review]
Otherwise it works fine:
https://github.com/ubiquibot-whilefoo-testing/testing/issues/13
https://github.com/ubiquibot-whilefoo-testing/testing/pull/10

File: src/comment.ts (hunk 1 above)
Comment (gentlementlegen) [reply src/comment.ts:138]: No, this is a mistake. Do you mean I introduced that during refactoring or was that like this before?

File: src/comment.ts (hunk 2 above)
Comment (gentlementlegen) [reply src/comment.ts:8]: That's a good point. To fix it I believe this should be then stored in a new class to make sure it is not shared between instances, but then it would mean that `postComment` could not be called via a function but rather would need to come from some object, which might be inconvenient? Might have to move `postComment` inside of the context or something similar.

File: src/comment.ts (hunk 1 above)
Comment (gentlementlegen) [reply src/comment.ts]: Merged with the supplied metadata
https://github.com/ubiquity-os/plugin-sdk/pull/65/files/a8f92f7de9c2f316376a2ca00b8bea91cdc5c4cc..7a18787a212c0f9300aa4f2dfef0843f2f150fe3
https://github.com/Meniole/plugin-template/issues/1#issuecomment-2638310831

File: src/comment.ts (hunk 2 above)
Comment (gentlementlegen) [reply src/comment.ts]: @whilefoo Wrapped the comment posting inside of a class, and exposed it from the context:
https://github.com/ubiquity-os/plugin-sdk/pull/65/commits/da526ffb2dbb4b008af87f60e7755c4f12922af2

I believe this is important to address because I actually have noticed the behavior you mentioned
https://github.com/ubiquity/ubiquity-dollar/issues/985#issuecomment-2637844777

This will require changes from all the plugins sadly.

File: src/comment.ts (hunk 1 above)
Comment (whilefoo) [reply src/comment.ts]: Yeah it was like that from beginning but I've only noticed now

**Review by whilefoo — APPROVED** [review]

File: src/comment.ts (hunk 2 above)
Comment (whilefoo) [reply src/comment.ts]: Maybe Context should become a class in the future
